export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/login/index',
    'pages/ticket-notice/index',
    'pages/ticket-buy/index',
    'pages/ticket-use/index',
    'pages/order-review/index',
    'pages/order-detail/index',
    'pages/user-update/index',
    'pages/clause-list/index',
    'pages/clause-privacy-policy/index',
    'pages/clause-farm-notice/index',
    'pages/clause-disclaimers/index',
    'pages/about-us/index',
    'pages/activity-blind-box/index',
    'pages/activity-curriculum/index',
    'pages/activity-cooperation/index',
    'pages/activity-all-day-ticket/index',
    'pages/reward-list/index',
    'pages/reward-detail/index',
    'pages/vip-center/index',
    'pages/coupon-use/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
});
